WITH CALC_TICKET_NUM AS (
    SELECT 
        P.PASSENGER_ID, 
        F.FLIGHT_ID, 
        F.CAPACITY, 
        ROW_NUMBER() OVER(PARTITION BY F.FLIGHT_ID) AS TICKET_NUM 
    FROM FLIGHTS F 
    INNER JOIN  PASSENGERS P 
    ON P.FLIGHT_ID = F.FLIGHT_ID
)

SELECT 
    F.FLIGHT_ID, 
    SUM(
        CASE WHEN S.TICKET_NUM <= S.CAPACITY THEN 1 ELSE 0 END 
    ) AS BOOKED_CNT, 
    SUM(
        CASE WHEN S.TICKET_NUM > S.CAPACITY THEN 1 ELSE 0 END 
    ) AS WAITLIST_CNT
FROM FLIGHTS F 
LEFT JOIN CALC_TICKET_NUM S
ON F.FLIGHT_ID = S.FLIGHT_ID
GROUP BY F.FLIGHT_ID 
ORDER BY FLIGHT_ID ASC