WITH 
    CALC_VOTE_CNTRB AS(
        SELECT 
            VOTER, 
            1 / COUNT(*) AS VOTE_CNTRB
        FROM VOTES 
        GROUP BY VOTER 
    ), 

    CALC_CANDIDATE_VOTES AS (
        SELECT 
            L.CANDIDATE, 
            SUM(R.VOTE_CNTRB) AS TOTAL_VOTES
        FROM VOTES L 
        INNER JOIN CALC_VOTE_CNTRB R 
        ON L.VOTER = R.VOTER 
        GROUP BY L.CANDIDATE  
         
    )

SELECT 
    CANDIDATE 
FROM CALC_CANDIDATE_VOTES 
WHERE TOTAL_VOTES = (
    SELECT MAX(TOTAL_VOTES) FROM CALC_CANDIDATE_VOTES
)
ORDER BY CANDIDATE ASC
