WITH 
    GET_TRIP_STATS AS (
        SELECT 
            *, 
            DISTANCE_KM / FUEL_CONSUMED AS FUEL_EFFICIENCY, 
            CASE
                WHEN MONTH(TRIP_DATE) BETWEEN 1 AND 6 THEN 'FIRST_HALF'
                WHEN MONTH(TRIP_DATE) BETWEEN 7 AND 12 THEN 'SECOND_HALF'
                ELSE NULL
            END AS TRIP_CATG
        FROM TRIPS 
    ), 

    COMPARE_FUEL_EFF AS (
        SELECT 
            L.DRIVER_ID,
            SUM(L.FUEL_EFFICIENCY) / COUNT(*) AS FIRST_HALF_AVG, 
            SUM(R.FUEL_EFFICIENCY) / COUNT(*) AS SECOND_HALF_AVG 
        FROM GET_TRIP_STATS L 
        INNER JOIN GET_TRIP_STATS R
        ON 
            L.DRIVER_ID = R.DRIVER_ID 
            AND L.TRIP_CATG = 'FIRST_HALF' 
            AND R.TRIP_CATG = 'SECOND_HALF'
        GROUP BY L.DRIVER_ID
    ) 

SELECT 
    F.DRIVER_ID AS driver_id, 
    D.DRIVER_NAME AS driver_name, 
    ROUND(F.FIRST_HALF_AVG, 2) AS first_half_avg, 
    ROUND(F.SECOND_HALF_AVG, 2) AS second_half_avg, 
    ROUND(F.SECOND_HALF_AVG - F.FIRST_HALF_AVG, 2) AS efficiency_improvement 
FROM COMPARE_FUEL_EFF F
INNER JOIN DRIVERS D 
ON F.DRIVER_ID = D.DRIVER_ID 
AND F.SECOND_HALF_AVG - F.FIRST_HALF_AVG > 0
ORDER BY EFFICIENCY_IMPROVEMENT DESC, DRIVER_NAME ASC